### ISSUE TITLE
Support for win32  or win64

### ISSUE THREAD

**Issue by ccls00** [hertzg/node-net-keepalive#14]
Support for win32  or win64

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for net-keepalive@1.2.1: wanted {"os":"freebsd,darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    freebsd,darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

  "os": [
    "freebsd",
    "darwin",
    "linux"
  ],

**Comment by hertzg** [comment]
This was asked before (#5) and right now windows is not supported. If you can provide a PR with it I would gladly merge it.
