### ISSUE TITLE
node-addon-api vulnerability reported, upgrade to v2.0.1 or higher

### ISSUE THREAD

**Issue by RMutharaju** [hertzg/node-net-keepalive#24]
Hello,

I see a vulnerability reported with node-addon-api - (because of DevDependencies) 

Refer:
https://snyk.io/vuln/SNYK-JS-NODEADDONAPI-571001

Kindly upgrade the node version as proposed.

Thanks.

**Comment by hertzg** [comment]
Bumping `ffi-napi` a patch version higher should include the newer version of `node-addon-api`.

**Comment by hertzg** [comment]
Landed in `net-keepalive@1.3.2`

**Comment by hertzg** [comment]
@all-contributors please add @RMutharaju for security
