### ISSUE TITLE
node 5.x: v8::ArrayBuffer::Neuter

### ISSUE THREAD

**Issue by mkozjak** [hertzg/node-net-keepalive#3]
When trying to use this library with node v5.0.0 (linux), I get

```FATAL ERROR: v8::ArrayBuffer::Neuter Only externalized ArrayBuffers can be neutered
zsh: abort      node index.js```

Works okay on 4.2.2 (linux).

**Comment by mkozjak** [comment]
Works okay on v5.1.0, too.

**Comment by hertzg** [comment]
@mkozjak Most likely some changes in v8 caused issue with `nan`/`ffi`/`ref`.
I've added node v5 to Travis CI and all test are passing.

**Comment by hertzg** [comment]
@all-contributors please add @mkozjak for bug
