### ISSUE TITLE
GLIBCXX_3.4.29 not found - AWS Platform Node.js 18 running on 64bit Amazon Linux 2/5.8.2

### ISSUE THREAD

**Issue by ikb42** [hertzg/node-net-keepalive#303]
**Describe the bug**
When running under Elastic Beanstalk AWS Platform Node.js 18 on 64bit Amazon Linux 2/5.8.2, the app reports an error on startup:

`/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /var/app/current/node_modules/ffi-napi/build/Release/ffi_bindings.node)`

**To Reproduce**
Use library on AWS Platform Node.js 18 running on 64bit Amazon Linux 2/5.8.2

**Expected behavior**
Error is thrown on app startup

**Screenshots or Screencasts**
reported also in ffi-napi - https://github.com/node-ffi-napi/node-ffi-napi/issues/252

**Package (please complete the following information):**
 - OS: Elastic Beanstalk AWS Platform Node.js 18 on 64bit Amazon Linux 2/5.8.2
 - Node: v18
 - Version: v3.0.0

**Additional context**
This seems to be an issue with a dependency "ffi-napi"

**Comment by hertzg** [comment]
> This seems to be an issue with a dependency "ffi-napi"

Correct observation, not much I can do until it's resolved upstream.

**Comment by ikb42** [comment]
@hertzg I see couple ppl mentioning this as an alternative which appears to be being maintained [https://www.npmjs.com/package/koffi]

Not sure what it would take to switch to that?

**Comment by hertzg** [comment]
Most of the binding stuff happens in `/lib/ffi-bindings.js` file I'd suggest starting from there.

https://github.com/hertzg/node-net-keepalive/blob/7b2732389438d0cf7178c1ff7c18d6a967bc7b64/lib/ffi-bindings.js#L10-L17

it exposes the two main function

https://github.com/hertzg/node-net-keepalive/blob/7b2732389438d0cf7178c1ff7c18d6a967bc7b64/lib/ffi-bindings.js#L62-L65

that are later used in specific end user functions

https://github.com/hertzg/node-net-keepalive/blob/7b2732389438d0cf7178c1ff7c18d6a967bc7b64/lib/ffi-bindings.js#L62-L65

https://github.com/hertzg/node-net-keepalive/blob/7b2732389438d0cf7178c1ff7c18d6a967bc7b64/lib/index.js#L120-L126

and so on.

**Comment by hertzg** [comment]
closing this since there's not much else to do here, feel free to submit a PR 🙌

**Comment by ikb42** [comment]
Hi, just a quick update on this in case useful to someone.
It seems in my case, AWS Platform Node.js 18 running on 64bit Amazon Linux 2/5.8.2 is using glib 2.56 (2018 - 2021) whereas the newer version of Amazon Linux is using glib 2.74.  
This later version apparently fixes the issue - although it is not yet available to select as an option in Elastic Beanstalk.  I'll come back here once there is an update.

**Comment by ikb42** [comment]
Final update on this - TL;DR it works now!

AWS have released their EB managed Node 18 with Amazon Linux 2023, this package works without modification.
See "Node.js 18 running on 64bit Amazon Linux 2023/6.0.0"

**Comment by hertzg** [comment]
@all-contributors please add @ikb42 for bug

**Comment by hertzg** [comment]
@all-contributors please add @ikb42 for bug
