### ISSUE TITLE
Missing support for freebsd

### ISSUE THREAD

**Issue by ggsubs** [hertzg/node-net-keepalive#4]
Can you please consider freebsd - there's a large FreeNAS base running on it. The platform specific dependency, ffi is supported on freebsd.

```47 error FreeBSD 10.3-STABLE
48 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "net-keepalive"
49 error node v6.7.0
50 error npm  v3.9.2
51 error code EBADPLATFORM
52 error notsup Not compatible with your operating system or architecture: net-keepalive@0.3.8
53 error notsup Valid OS:    darwin,linux,!win32
53 error notsup Valid Arch:  any
53 error notsup Actual OS:   freebsd
53 error notsup Actual Arch: x64
54 verbose exit [ 1, true ]```

**Comment by hertzg** [comment]
Sorry for the late reply. I'm not familiar with FreeBSD at all I'll try to look into it, but pull requests are welcome.

**Comment by hertzg** [comment]
I've submitted an experimental version 71bce16, give it a try

**Comment by hertzg** [comment]
Im going to close this for now

**Comment by hertzg** [comment]
@all-contributors please add @ggsubs for bug
