### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by armenthiz** [hertzg/node-net-keepalive#5]
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "net-keepalive"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: net-keepalive@0.3.8
npm ERR! notsup Valid OS:    darwin,linux,!win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

thank you very much..

**Comment by hertzg** [comment]
Windows is not supported at the moment. And implementing and testing it requires a lot of time and effort which I don't have for now. Besides, I do not have Windows to test it on.

But Pull requests are welcome if anyone is willing to implement Winsock IOCTLs.

/ref https://msdn.microsoft.com/en-us/library/windows/desktop/dd877220(v=vs.85).aspx

**Comment by clshortfuse** [comment]
You can try to use https://github.com/clshortfuse/node-getsockethandleaddress

I use it like this:

```
/** @type {ffi.ForeignFunction} */
let setsockopt;

/**
 * @param {Socket} socket
 * @param {number} level
 * @param {number} option
 * @param {number|boolean} value
 * @return {number}
 */
function setSocketOption(socket, level, option, value) {
  const handle = socket._handle;
  if (!setsockopt) {
    const library = isWin32 ? 'ws2_32.dll' : null;
    const paramTypes = [
      ref.types.int,
      ref.types.int,
      ref.types.int,
      ref.refType(ref.types.void),
      isWin32 ? ref.types.int : ref.refType(ref.types.int),
    ];
    const lib = new ffi.DynamicLibrary(library);
    setsockopt = ffi.ForeignFunction(
      lib.get('setsockopt'),
      ref.types.int, paramTypes
    );
  }
  const refType = (typeof value === 'boolean' ? ref.types.bool : ref.types.int);
  const handleAddress = getSocketHandleAddress.getAddress(handle);
  if (!isWin32) {
    return setsockopt(
      handleAddress,
      level, option, ref.alloc(refType, value), ref.alloc(ref.types.int, refType.size)
    );
  }
  return setsockopt(
    handleAddress,
    level, option, ref.alloc(refType, value), refType.size
  );
}
```

I've been using for `SO_OOBINLINE` for about 2 years now. I can publish it to npm if you're interested in using it.

**Comment by hertzg** [comment]
@clshortfuse if you are willing to make a pull request that would be geat.
